# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tubelet_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tubelet_service.proto',
  package='tubelet_service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15tubelet_service.proto\x12\x0ftubelet_service\"\x07\n\x05\x45mpty\"\x1f\n\x07point2d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"0\n\x0bobservation\x12\x13\n\x0b\x63lass_index\x18\x01 \x01(\r\x12\x0c\n\x04prob\x18\x02 \x01(\x01\"f\n\ttubelet2d\x12%\n\x03pos\x18\x01 \x01(\x0b\x32\x18.tubelet_service.point2d\x12\x32\n\x0cobservations\x18\x02 \x03(\x0b\x32\x1c.tubelet_service.observation\"\'\n\x14get_version_response\x12\x0f\n\x07version\x18\x01 \x01(\t\"m\n\x19\x61\x64\x64_observation2d_request\x12%\n\x03pos\x18\x01 \x01(\x0b\x32\x18.tubelet_service.point2d\x12)\n\x03obs\x18\x02 \x01(\x0b\x32\x1c.tubelet_service.observation\"K\n\x1bget_all_tubelets2d_response\x12,\n\x08tubelets\x18\x01 \x03(\x0b\x32\x1a.tubelet_service.tubelet2d\"-\n\x13move_window_request\x12\n\n\x02\x64x\x18\x01 \x01(\x01\x12\n\n\x02\x64y\x18\x02 \x01(\x01\"5\n\x1bset_window_position_request\x12\n\n\x02x0\x18\x01 \x01(\x01\x12\n\n\x02y0\x18\x02 \x01(\x01\x32\xbd\x04\n\x0ftubelet_service\x12N\n\x0bget_version\x12\x16.tubelet_service.Empty\x1a%.tubelet_service.get_version_response\"\x00\x12Y\n\x11\x61\x64\x64_observation2d\x12*.tubelet_service.add_observation2d_request\x1a\x16.tubelet_service.Empty\"\x00\x12\\\n\x12get_all_tubelets2d\x12\x16.tubelet_service.Empty\x1a,.tubelet_service.get_all_tubelets2d_response\"\x00\x12\x39\n\x05reset\x12\x16.tubelet_service.Empty\x1a\x16.tubelet_service.Empty\"\x00\x12\x38\n\x04\x63lip\x12\x16.tubelet_service.Empty\x1a\x16.tubelet_service.Empty\"\x00\x12M\n\x0bmove_window\x12$.tubelet_service.move_window_request\x1a\x16.tubelet_service.Empty\"\x00\x12]\n\x13set_window_position\x12,.tubelet_service.set_window_position_request\x1a\x16.tubelet_service.Empty\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='tubelet_service.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=49,
)


_POINT2D = _descriptor.Descriptor(
  name='point2d',
  full_name='tubelet_service.point2d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='tubelet_service.point2d.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='tubelet_service.point2d.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=82,
)


_OBSERVATION = _descriptor.Descriptor(
  name='observation',
  full_name='tubelet_service.observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class_index', full_name='tubelet_service.observation.class_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prob', full_name='tubelet_service.observation.prob', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=132,
)


_TUBELET2D = _descriptor.Descriptor(
  name='tubelet2d',
  full_name='tubelet_service.tubelet2d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='tubelet_service.tubelet2d.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observations', full_name='tubelet_service.tubelet2d.observations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=236,
)


_GET_VERSION_RESPONSE = _descriptor.Descriptor(
  name='get_version_response',
  full_name='tubelet_service.get_version_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='tubelet_service.get_version_response.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=277,
)


_ADD_OBSERVATION2D_REQUEST = _descriptor.Descriptor(
  name='add_observation2d_request',
  full_name='tubelet_service.add_observation2d_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='tubelet_service.add_observation2d_request.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obs', full_name='tubelet_service.add_observation2d_request.obs', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=388,
)


_GET_ALL_TUBELETS2D_RESPONSE = _descriptor.Descriptor(
  name='get_all_tubelets2d_response',
  full_name='tubelet_service.get_all_tubelets2d_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tubelets', full_name='tubelet_service.get_all_tubelets2d_response.tubelets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=465,
)


_MOVE_WINDOW_REQUEST = _descriptor.Descriptor(
  name='move_window_request',
  full_name='tubelet_service.move_window_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dx', full_name='tubelet_service.move_window_request.dx', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dy', full_name='tubelet_service.move_window_request.dy', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=512,
)


_SET_WINDOW_POSITION_REQUEST = _descriptor.Descriptor(
  name='set_window_position_request',
  full_name='tubelet_service.set_window_position_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x0', full_name='tubelet_service.set_window_position_request.x0', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y0', full_name='tubelet_service.set_window_position_request.y0', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=567,
)

_TUBELET2D.fields_by_name['pos'].message_type = _POINT2D
_TUBELET2D.fields_by_name['observations'].message_type = _OBSERVATION
_ADD_OBSERVATION2D_REQUEST.fields_by_name['pos'].message_type = _POINT2D
_ADD_OBSERVATION2D_REQUEST.fields_by_name['obs'].message_type = _OBSERVATION
_GET_ALL_TUBELETS2D_RESPONSE.fields_by_name['tubelets'].message_type = _TUBELET2D
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['point2d'] = _POINT2D
DESCRIPTOR.message_types_by_name['observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['tubelet2d'] = _TUBELET2D
DESCRIPTOR.message_types_by_name['get_version_response'] = _GET_VERSION_RESPONSE
DESCRIPTOR.message_types_by_name['add_observation2d_request'] = _ADD_OBSERVATION2D_REQUEST
DESCRIPTOR.message_types_by_name['get_all_tubelets2d_response'] = _GET_ALL_TUBELETS2D_RESPONSE
DESCRIPTOR.message_types_by_name['move_window_request'] = _MOVE_WINDOW_REQUEST
DESCRIPTOR.message_types_by_name['set_window_position_request'] = _SET_WINDOW_POSITION_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.Empty)
  })
_sym_db.RegisterMessage(Empty)

point2d = _reflection.GeneratedProtocolMessageType('point2d', (_message.Message,), {
  'DESCRIPTOR' : _POINT2D,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.point2d)
  })
_sym_db.RegisterMessage(point2d)

observation = _reflection.GeneratedProtocolMessageType('observation', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATION,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.observation)
  })
_sym_db.RegisterMessage(observation)

tubelet2d = _reflection.GeneratedProtocolMessageType('tubelet2d', (_message.Message,), {
  'DESCRIPTOR' : _TUBELET2D,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.tubelet2d)
  })
_sym_db.RegisterMessage(tubelet2d)

get_version_response = _reflection.GeneratedProtocolMessageType('get_version_response', (_message.Message,), {
  'DESCRIPTOR' : _GET_VERSION_RESPONSE,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.get_version_response)
  })
_sym_db.RegisterMessage(get_version_response)

add_observation2d_request = _reflection.GeneratedProtocolMessageType('add_observation2d_request', (_message.Message,), {
  'DESCRIPTOR' : _ADD_OBSERVATION2D_REQUEST,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.add_observation2d_request)
  })
_sym_db.RegisterMessage(add_observation2d_request)

get_all_tubelets2d_response = _reflection.GeneratedProtocolMessageType('get_all_tubelets2d_response', (_message.Message,), {
  'DESCRIPTOR' : _GET_ALL_TUBELETS2D_RESPONSE,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.get_all_tubelets2d_response)
  })
_sym_db.RegisterMessage(get_all_tubelets2d_response)

move_window_request = _reflection.GeneratedProtocolMessageType('move_window_request', (_message.Message,), {
  'DESCRIPTOR' : _MOVE_WINDOW_REQUEST,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.move_window_request)
  })
_sym_db.RegisterMessage(move_window_request)

set_window_position_request = _reflection.GeneratedProtocolMessageType('set_window_position_request', (_message.Message,), {
  'DESCRIPTOR' : _SET_WINDOW_POSITION_REQUEST,
  '__module__' : 'tubelet_service_pb2'
  # @@protoc_insertion_point(class_scope:tubelet_service.set_window_position_request)
  })
_sym_db.RegisterMessage(set_window_position_request)



_TUBELET_SERVICE = _descriptor.ServiceDescriptor(
  name='tubelet_service',
  full_name='tubelet_service.tubelet_service',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=570,
  serialized_end=1143,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_version',
    full_name='tubelet_service.tubelet_service.get_version',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_GET_VERSION_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='add_observation2d',
    full_name='tubelet_service.tubelet_service.add_observation2d',
    index=1,
    containing_service=None,
    input_type=_ADD_OBSERVATION2D_REQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_all_tubelets2d',
    full_name='tubelet_service.tubelet_service.get_all_tubelets2d',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_GET_ALL_TUBELETS2D_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='reset',
    full_name='tubelet_service.tubelet_service.reset',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='clip',
    full_name='tubelet_service.tubelet_service.clip',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='move_window',
    full_name='tubelet_service.tubelet_service.move_window',
    index=5,
    containing_service=None,
    input_type=_MOVE_WINDOW_REQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='set_window_position',
    full_name='tubelet_service.tubelet_service.set_window_position',
    index=6,
    containing_service=None,
    input_type=_SET_WINDOW_POSITION_REQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TUBELET_SERVICE)

DESCRIPTOR.services_by_name['tubelet_service'] = _TUBELET_SERVICE

# @@protoc_insertion_point(module_scope)
